name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          version: 12
      - name: test
        run: |
          npm i
          npm run test -- --silent
