name: test
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          version: 12
      - name: test
        run: npm run test -- --silent
