name: build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: build
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          version: 12
      - run: npm run build
      - name: test
      - run: npm run test -- --silent
